import type { Metadata } from "next";


export const metadata: Metadata = {
    title: { default: "About", template: '' },
    description: "Generated by create next app",
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className="main">
            {children}
        </main>
    );
}
