'use client';

import React from 'react'
import { AboutItem } from './_components/AboutItem';
import './style.scss'
import MainWrapper from '@/components/wrapper/MainWrapper';
import NotificationsCard from '@/components/NotificationsCard';
// export const metadata: Metadata = {
//     title: 'About',
//     description: "Generated by create next app",
// };


export default function AboutPage() {

    return (
        <MainWrapper>
            <div className='flex flex-col gap-6'>

                <NotificationsCard username='faisalamin' />
                <div className="about-section">
                    <h1>About Us</h1>
                    <p>SteemPro is the Steem blockchain's decentralized mobile and web app solution. It will allow the end user to perform all broadcast operations easily and securely with some additioanl benifits.
                        Web version also includes useful tools to analyze the author progress on this platform.
                    </p>
                </div>

                <h2 className='text-2xl font-bold text-center'>
                    Our Team</h2>
                <div className="flex flex-col md:flex-row gap-6 justify-center p-4">

                    <AboutItem username={'steempro.com'}
                        firstHeading={'Official Account'}
                        secondHeading={'steempro.official@gmail.com'}
                    />

                    <AboutItem username={'faisalamin'}
                        firstHeading={'Core Developer'}
                        secondHeading={'steempro.official@gmail.com'}
                    />




                </div>
            </div>
        </MainWrapper>
    )
}
