import moment from "moment";
import { RewardTypes } from "./AppConstants";

export const empty_comment = (
  author: string,
  permlink: string,
  body?: string,
  author_role?: RoleTypes,
  author_title?: string
): Post => {
  const timenow = moment().unix();
  return {
    link_id: timenow,
    link_status: 1,
    author_reputation: 0,
    author_status: 1,
    author_role: author_role ?? "guest",
    author_title: author_title ?? "",
    author: author,
    permlink: permlink,
    parent_author: "",
    parent_permlink: "",
    root_author: "",
    root_permlink: "",
    root_title: "",
    created: timenow - 150000,
    payout_comments: 0,
    downvote_weight: 0,
    last_update: timenow - 150000,
    last_sync: 0,
    cashout_time: 0,
    payout: 0,
    total_payout_value: 0,
    curator_payout_value: 0,
    pending_payout_value: 0,
    promoted: 0,
    net_rshares: 0,
    total_vote_weight: 0,
    max_accepted_payout: 0,
    percent_steem_dollars: 0,
    allow_curation_rewards: 0,
    allow_replies: 1,
    allow_votes: 1,
    depth: 0,
    last_reply: 0,
    children: 0,
    resteem_count: 0,
    upvote_count: 0,
    downvote_count: 0,
    word_count: 0,
    is_muted: 0,
    is_pinned: 0,
    category: "",
    community: "",
    json_metadata: "",
    title: "",
    body: body ?? "",
    beneficiaries: [],
    votes: [],
    observer_follows_author: 0,
    observer_ignores_author: 0,
    observer_resteem: 0,
    observer_role: "guest",
    observer_title: "",
    observer_vote: 0,
    observer_vote_percent: 0,
    observer_vote_rshares: 0,
    replies: [],
    json_images: "",
    is_author_muted: 0,
    status: "idle",
    is_new: 1,
    parent_link_id: 0,
  };
};

export const empty_profile = (name: string): AccountExt => {
  const timenow = moment().unix();
  return {
    name: name,
    creator: "",
    recovery_account: "",
    reset_account: "",
    proxy: "",
    json_metadata: "",
    posting_json_metadata: "{}",
    created: 0,
    last_action: 0,
    last_comment: 0,
    last_root_post: 0,
    last_vote: 0,
    last_account_recovery: 0,
    last_account_update: 0,
    last_owner_update: 0,
    last_update: 0,
    last_sync: 0,
    reputation: 0,
    voting_csi: 0,
    selfvote_rate: 0,
    curation_rewards: 0,
    posting_rewards: 0,
    mined: 0,
    can_vote: 0,
    count_comments: 0,
    count_root_posts: 0,
    count_active_posts: 0,
    count_replies: 0,
    count_upvotes: 0,
    count_upvoted: 0,
    count_downvotes: 0,
    count_downvoted: 0,
    count_followers: 0,
    count_following: 0,
    balance_steem: 0,
    balance_sbd: 0,
    rewards_steem: 0,
    rewards_sbd: 0,
    rewards_vests: 0,
    savings_steem: 0,
    savings_sbd: 0,
    vests_own: 0,
    vests_in: 0,
    vests_out: 0,
    powerdown: 0,
    powerdown_done: 0,
    powerdown_rate: 0,
    next_powerdown: 0,
    upvote_mana_current: 0,
    upvote_mana_max: 0,
    upvote_mana_percent: 0,
    upvote_mana_last_update: 0,
    downvote_mana_current: 0,
    downvote_mana_max: 0,
    downvote_mana_percent: 0,
    downvote_mana_last_update: 0,
    rc_mana_current: 0,
    rc_mana_max: 0,
    rc_mana_percent: 0,
    rc_mana_last_update: 0,
    witness_votes: [],
    withdraw_routes: 0,
    savings_withdraw_requests: 0,
    pending_claimed_accounts: 0,
    sbd_seconds: "0",
    sbd_seconds_last_update: 0,
    sbd_last_interest_payment: 0,
    savings_sbd_seconds: "0",
    savings_sbd_seconds_last_update: 0,
    savings_sbd_last_interest_payment: 0,
    owner_account_auths: [],
    owner_weight_threshold: 0,
    owner_key_auths: [],
    active_account_auths: [],
    active_key_auths: [],
    active_weight_threshold: 0,
    posting_account_auths: [],
    posting_key_auths: [],
    posting_weight_threshold: 0,
    memo_key: "",
    login: false,
    communities: [],
    last_fetch: timenow,
    observer_follows_author: 0,
    observer_ignores_author: 0,
    encKey: "",
    status: "idle",
    proxied_vsf_votes: [],
  };
};

export const empty_draft = (): PostDraft => {
  return {
    title: "",
    body: "",
    tags: [],
    category: "",
    community: undefined,
    beneficiaries: [],
    reward: RewardTypes[1],
  };
};

export const empty_community = (
  account: string,
  title?: string | null
): Community => {
  return {
    id: 0,
    type: "topic",
    account: account,
    account_reputation: 25,
    created: 0,
    rank: 0,
    sum_pending: 0,
    count_pending: 0,
    count_authors: 0,
    count_subs: 0,
    lang: "",
    title: title || "",
    about: "",
    description: "",
    flag_text: "",
    is_nsfw: 0,
    settings: {},
    observer_subscribed: 0,
    observer_role: "guest",
    observer_title: "",
    status: "idle",
    roles: [],
  };
};

export const empty_settings = (): Setting => {
  return {
    lang: { code: "en", title: "English" },
    nsfw: "Always warn",
    feedStyle: "list",
    rpc: "https://api.steemit.com",
    theme: "system",
    readMore: true,
    voteOptions: {
      remember: true,
      value: 100,
    },
    longPressVote: {
      enabled: false,
      usersList: [],
    },
    favouriteBene:[]
  };
};
