import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import './markdown.scss';
import { Providers } from "./providers";
import { Toaster } from "sonner";
import clsx from "clsx";
// import 'react-toastify/dist/ReactToastify.css';
// import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "SteemPro",
    template: '%s | SteemPro',
    absolute: '',
  },
  description: "Generated by create next app",
  icons: {
    icon: '/logo192.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={clsx(inter.className,)}>
        <Providers>
          {children}
          <Toaster richColors />
        </Providers>
      </body>
    </html>
  );
}
