import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import './markdown.scss';
import { Providers } from "./providers";
import { Toaster } from "sonner";
import clsx from "clsx";
import { getAuthorExt } from "@/libs/steem/sds";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "SteemPro",
    template: '%s | SteemPro',
    absolute: '',
  },
  description: "Generated by create next app",
  icons: {
    icon: '/logo192.png'
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const session = await getServerSession();
  let data;
  if (session?.user?.name)
    data = await getAuthorExt(session?.user?.name)



  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={clsx(inter.className,)}>
        <Providers data={data}>
          {children}
          <Toaster richColors />
        </Providers>
      </body>
    </html>
  );
}
